### ISSUE TITLE
Potential bug when removing entities from r-tree

### ISSUE THREAD

**Issue by cBournhonesque** [laundmo/bevy-spatial#11]
I think there might be a bug in the library. I've been using it with only 2 moving entities. Most of the time it works fine, the r-tree gets updated correctly. (i.e. the size of the r-tree is constant and the r-tree gets updated for my 2 moving entities)
But there are periods of time where the old entities don't get removed correctly from the r-tree. I think it comes from here: https://github.com/laundmo/bevy-spatial/blob/main/src/spatial_access.rs#L118

If I understand correctly, this creates a 'fake point' at (0.0, 0.0) to be removed from the r-tree. The removal uses PartialEq which only uses entity values. However the r-star docs mention: https://docs.rs/rstar/latest/rstar/struct.RTree.html#method.remove that the removal will only work correctly if two equal elements also have the same envelope. That's not the case for the `remove_entity` function.

I think I got this bug pretty quickly because my PR (https://github.com/laundmo/bevy-spatial/pull/10/files#diff-e37139dbfd90c98ea5c8fc2a21bfaa1082e5e0aab5e13ba7dc049afba79fb7c6R101)  switches to using `remove_entity` instead of using the previous position, so I use `remove_entity` a lot more than before. (i.e. in every update)

I'm not 100% sure this is the problem, but one solution could be to maintain a map from Entity -> Position for every position in the r-tree

**Comment by laundmo** [comment]
hmm, interesting. i wonder what the crates official way of dealing with this is - there must be a way to just remove by id

**Comment by laundmo** [comment]
seems like a case where the only way is to test it, i'll whip up a test tomorrow and see

**Comment by cBournhonesque** [comment]
Thanks, please let me know!
I don't think the crate has a way to deal with this, they seem to rely only on envelopes to traverse the tree and find the element.

**Comment by laundmo** [comment]
just to note, we should have the last coordinate in the RTreeTracked component - querying that for removal should be possible

**Comment by cBournhonesque** [comment]
> just to note, we should have the last coordinate in the RTreeTracked component - querying that for removal should be possible

Yep, unless the entity has been despawned (in which case the RTreeTracked component has been despawned as well)

**Comment by cBournhonesque** [comment]
I added a global `HashMap<Entity, Point>` in the resource to keep track of last positions, and updated `add_point` and `remove_point` to always remove using the last position and the problem disappeared on my mind; so it looks like that was it!
The global hashmap also means that we don't need the `MovementTracker` component, which simplifies things a bit

**Comment by laundmo** [comment]
Nice! do you wanna PR this or should i do the honors
