### ISSUE TITLE
Consider removing distance check for recreating/updating

### ISSUE THREAD

**Issue by laundmo** [laundmo/bevy-spatial#13]
having used the crate a bunch myself, and having seen some projects using it, i don't think this feature is used at all and it only adds complexity.

I'll leave this issue up a bit and see if theres any voices against removing it.

**Comment by cBournhonesque** [comment]
I think with https://github.com/laundmo/bevy-spatial/pull/14 it's fine to leave it.
We'll need the last-position hashmap for correct removals anyway, so the distance-check won't add much complexity
