### ISSUE TITLE
Make TimestepElapsed pub

### ISSUE THREAD

**Issue by pinkponk** [laundmo/bevy-spatial#4]
I'm making a game where time can run at different speed and I would like to only update the tree every X frames or Y in game seconds. For that I would need to modify the timer inside the TimestepElapsed resource but it is not exposed as pub. Exposing the resource or adding an option to change update frequency dynamically would be great.

**Comment by laundmo** [comment]
This seems like a reasonable change, I've put it on my TODO. unless you would want to PR it?

**Comment by pinkponk** [comment]
Created a PR. If you merge it then also close this issue. Just started using your lib seems pretty nice great work. This was EXACTLY what I needed and was sure I would have to write it myself so thank you for making this.

**Comment by laundmo** [comment]
this is now finally in a release: https://github.com/laundmo/bevy-spatial/releases/tag/0.3.0
